# CDP1802 DIP definition
# https://github.com/tgtakaoka/dip
name = "CDP1802"
title = "CDP1802/CDP1806"
dip = 40
width = 600
1 = "CLOCK"
2 = "#WAIT"
3 = "#CLEAR"
4 = "Q"
5 = "SC1"
6 = "SC0"
7 = "#MRD"
8 = "D7"
9 = "D6"
10 = "D5"
11 = "D4"
12 = "D3"
13 = "D2"
14 = "D1"
15 = "D0"
16 = "VCC"
17 = "N2"
18 = "N1"
19 = "N0"
20 = "VSS"
21 = "#EF4"
22 = "#EF3"
23 = "#EF2"
24 = "#EF1"
25 = "A0/A8"
26 = "A1/A9"
27 = "A2/A10"
28 = "A3/A11"
29 = "A4/A12"
30 = "A5/A13"
31 = "A6/A14"
32 = "A7/A15"
33 = "TPB"
34 = "TPA"
35 = "#MWR"
36 = "#INT"
37 = "#DMAOUT"
38 = "#DMAIN"
39 = "#XTAL"
40 = "VDD"
