# HD6301 DIP definition
# https://github.com/tgtakaoka/dip
name = "HD6301V1P"
title = "HD6301V1P/HD6303R1P Mode2"
dip = 40
width = 600
1 = "VSS"
2 = "XTAL"
3 = "EXTAL"
4 = "#NMI"
5 = "#IRQ1"
6 = "#RESET"
7 = "#STBY"
8 = "P20, PC0"
9 = "P21, PC1"
10 = "P22, PC2"
11 = "P23"
12 = "P24"
13 = "P10"
14 = "P11"
15 = "P12"
16 = "P13"
17 = "P14"
18 = "P15"
19 = "P16"
20 = "P17"
21 = "VCC"
22 = "A15"
23 = "A14"
24 = "A13"
25 = "A12"
26 = "A11"
27 = "A10"
28 = "A9"
29 = "A8"
30 = "AD7"
31 = "AD6"
32 = "AD5"
33 = "AD4"
34 = "AD3"
35 = "AD2"
36 = "AD1"
37 = "AD0"
38 = "R/W"
39 = "AS"
40 = "E"
