# MC6809 DIP definition
# https://github.com/tgtakaoka/dip
name = "MC6809"
title = "MC6809/HD6309"
dip = 40
width = 600
1 = "VSS"
2 = "#NMI"
3 = "#IRQ"
4 = "#FIRQ"
5 = "BS"
6 = "BA"
7 = "VCC"
8 = "A0"
9 = "A1"
10 = "A2"
11 = "A3"
12 = "A4"
13 = "A5"
14 = "A6"
15 = "A7"
16 = "A8"
17 = "A9"
18 = "A10"
19 = "A11"
20 = "A12"
21 = "A13"
22 = "A14"
23 = "A15"
24 = "D7"
25 = "D6"
26 = "D5"
27 = "D4"
28 = "D3"
29 = "D2"
30 = "D1"
31 = "D0"
32 = "R/W"
33 = "#BREQ"
34 = "E"
35 = "Q"
36 = "MRDY"
37 = "#RESET"
38 = "EXTAL"
39 = "XTAL"
40 = "#HALT"
