# NS32016N DIP definition
# https://github.com/tgtakaoka/dip
name = "NS32016N"
dip = 48
width = 600
1 = "A22"
2 = "A21"
3 = "A20"
4 = "A19"
5 = "A18"
6 = "A17"
7 = "A16"
8 = "AD15"
9 = "AD14"
10 = "AD13"
11 = "AD12"
12 = "AD11"
13 = "AD10"
14 = "AD9"
15 = "AD8"
16 = "AD7"
17 = "AD6"
18 = "AD5"
19 = "AD4"
20 = "AD3"
21 = "AD2"
22 = "AD1"
23 = "AD0"
24 = "GNDL"
25 = "GNDB"
26 = "PHI1"
27 = "PHI2"
28 = "RDY"
29 = "BBG"
30 = "#HOLD"
31 = "#HLDA"
32 = "#HBE"
33 = "#DS, #FLT"
34 = "#RST, #ABT"
35 = "#AT, #SPC"
36 = "U/#S"
37 = "#ADS"
38 = "#DDIN"
39 = "#PFS"
40 = "ST3"
41 = "ST2"
42 = "ST1"
43 = "ST0"
44 = "#ILO"
45 = "#NMI"
46 = "#INT"
47 = "A23"
48 = "VCC"
