# NSC800N DIP definition
# https://github.com/tgtakaoka/dip
name = "NSC800N"
dip = 40
width = 600
1 = "A8"
2 = "A9"
3 = "A10"
4 = "A11"
5 = "A12"
6 = "A13"
7 = "A14"
8 = "A15"
9 = "CLK"
10 = "XOUT"
11 = "XIN"
12 = "AD0"
13 = "AD1"
14 = "AD2"
15 = "AD3"
16 = "AD4"
17 = "AD5"
18 = "AD6"
19 = "AD7"
20 = "GND"
21 = "#NMI"
22 = "#RSTA"
23 = "#RSTB"
24 = "#RSTC"
25 = "#INTR"
26 = "#INTA"
27 = "S1"
28 = "#RFSH"
29 = "S0"
30 = "ALE"
31 = "#WR"
32 = "#RD"
33 = "#RESET_IN"
34 = "IO/#M"
35 = "#BACK"
36 = "#BREQ"
37 = "RESET_OUT"
38 = "#WAIT"
39 = "#PS"
40 = "VCC"
