# P80C88 DIP definition
# https://github.com/tgtakaoka/dip
name = "P80C88A"
dip = 40
width = 600
1 = "GND"
2 = "A14"
3 = "A13"
4 = "A12"
5 = "A11"
6 = "A10"
7 = "A9"
8 = "A8"
9 = "AD7"
10 = "AD6"
11 = "AD5"
12 = "AD4"
13 = "AD3"
14 = "AD2"
15 = "AD1"
16 = "AD0"
17 = "NMI"
18 = "INTR"
19 = "CLK"
20 = "GND"
21 = "RESET"
22 = "READY"
23 = "#TEST"
24 = "#INTA, QS1"
25 = "ALE,   QS0"
26 = "#DEN,  #S0"
27 = "DT/#R, #S1"
28 = "M/#IO, #S2"
29 = "#WR,   #LOCK"
30 = "HLDA,  #RQ/GT1"
31 = "HOLD,  #RQ/GT0"
32 = "#RD"
33 = "MN,    #MX"
34 = "#SS0,  HIGH"
35 = "A19,   S6"
36 = "A18,   S5"
37 = "A17,   S4"
38 = "A16,   S3"
39 = "A15"
40 = "VCC"
