# R65C02 DIP definition
# https://github.com/tgtakaoka/dip
name = "R65C02"
title = "R65C02/G65SC02"
dip = 40
width = 600
1 = "VSS"
2 = "RDY"
3 = "PHI1O"
4 = "#IRQ"
5 = "NC"
6 = "#NMI"
7 = "SYNC"
8 = "VCC"
9 = "A0"
10 = "A1"
11 = "A2"
12 = "A3"
13 = "A4"
14 = "A5"
15 = "A6"
16 = "A7"
17 = "A8"
18 = "A9"
19 = "A10"
20 = "A11"
21 = "VSS"
22 = "A12"
23 = "A13"
24 = "A14"
25 = "A15"
26 = "D7"
27 = "D6"
28 = "D5"
29 = "D4"
30 = "D3"
31 = "D2"
32 = "D1"
33 = "D0"
34 = "R/W"
35 = "NC"
36 = "NC"
37 = "PHI0I"
38 = "#SO"
39 = "PHI2O"
40 = "#RES"
