# TMS320C15NL DIP definition
# https://github.com/tgtakaoka/dip
name = "TMS320C15"
title = "TMS320C15NL"
dip = 40
width = 600
1 = "A1/PA1"
2 = "A0/PA0"
3 = "MC/#MP"
4 = "#RS"
5 = "#INT"
6 = "CLKOUT"
7 = "X1"
8 = "X2/CLKIN"
9 = "#BIO"
10 = "Vss"
11 = "D8"
12 = "D9"
13 = "D10"
14 = "D11"
15 = "D12"
16 = "D13"
17 = "D14"
18 = "D15"
19 = "D7"
20 = "D6"
21 = "D5"
22 = "D4"
23 = "D3"
24 = "D2"
25 = "D1"
26 = "D0"
27 = "A11"
28 = "A10"
29 = "A9"
30 = "Vcc"
31 = "#WE"
32 = "#DEN"
33 = "#MEN"
34 = "A8"
35 = "A7"
36 = "A6"
37 = "A5"
38 = "A4"
39 = "A3"
40 = "A2/PA2"
