# TMS9995 DIP definition
# https://github.com/tgtakaoka/dip
name = "TMS9995"
dip = 40
width = 600
1 = "XTAL1"
2 = "XTAL2, CLKIN"
3 = "CLKOUT"
4 = "D7"
5 = "D6"
6 = "D5"
7 = "D4"
8 = "D3"
9 = "D2"
10 = "VCC"
11 = "D1"
12 = "D0"
13 = "CRUIN"
14 = "#INT4, #EC"
15 = "#INT1"
16 = "IQA, HOLDA"
17 = "#DBIN"
18 = "#HOLD"
19 = "#WE, #CRUCLK"
20 = "#MEMEN"
21 = "#NMI"
22 = "#RESET"
23 = "READY"
24 = "A0"
25 = "A1"
26 = "A2"
27 = "A3"
28 = "A4"
29 = "A5"
30 = "A6"
31 = "GND"
32 = "A7"
33 = "A8"
34 = "A9"
35 = "A10"
36 = "A11"
37 = "A12"
38 = "A13"
39 = "A14"
40 = "A15, CRUOUT"
