# Z8001 DIP definition
# https://github.com/tgtakaoka/dip
name = "Z16C01"
title = "Z08001/Z16C01 (Z8001)"
dip = 48
width = 600
1 = "AD0"
2 = "AD9"
3 = "AD10"
4 = "AD11"
5 = "AD12"
6 = "AD13"
7 = "#STOP"
8 = "#MI"
9 = "AD15"
10 = "AD14"
11 = "VCC"
12 = "#VI"
13 = "#NVI"
14 = "#SEGT"
15 = "#NMI"
16 = "#RESET"
17 = "#MO"
18 = "#MREQ"
19 = "#DS"
20 = "ST3"
21 = "ST2"
22 = "ST1"
23 = "ST0"
24 = "SN3"
25 = "SN1"
26 = "SN0"
27 = "#BUSREQ"
28 = "#WAIT"
29 = "#BUSACK"
30 = "R/W"
31 = "N/S"
32 = "B/W"
33 = "NC"
34 = "#AS"
35 = "CLOCK"
36 = "GND"
37 = "SN2"
38 = "AD1"
39 = "AD2"
40 = "AD3"
41 = "AD5"
42 = "SN4"
43 = "AD4"
44 = "AD6"
45 = "AD7"
46 = "SN5"
47 = "SN6"
48 = "AD6"
