# Z8002 DIP definition
# https://github.com/tgtakaoka/dip
name = "Z16C02"
title = "Z08002/Z16C02 (Z8002)"
dip = 40
width = 600
1 = "AD9"
2 = "AD10"
3 = "AD11"
4 = "AD12"
5 = "AD13"
6 = "#STOP"
7 = "#MI"
8 = "AD15"
9 = "AD14"
10 = "VCC"
11 = "#VI"
12 = "#NVI"
13 = "#NMI"
14 = "#RESET"
15 = "#MO"
16 = "#MREQ"
17 = "#DS"
18 = "ST3"
19 = "ST2"
20 = "ST1"
21 = "ST0"
22 = "#BUSREQ"
23 = "#WAIT"
24 = "#BUSACK"
25 = "R/W"
26 = "N/S"
27 = "B/W"
28 = "NC"
29 = "#AS"
30 = "CLOCK"
31 = "GND"
32 = "AD1"
33 = "AD2"
34 = "AD3"
35 = "AD5"
36 = "AD4"
37 = "AD6"
38 = "AD7"
39 = "AD8"
40 = "AD0"
