# Z80 DIP definition
# https://github.com/tgtakaoka/dip
name = "Z84C00"
title = "Z84C00 (Z80)"
dip = 40
width = 600
1 = "A11"
2 = "A12"
3 = "A13"
4 = "A14"
5 = "A15"
6 = "CLK"
7 = "D4"
8 = "D3"
9 = "D5"
10 = "D6"
11 = "VCC"
12 = "D2"
13 = "D7"
14 = "D0"
15 = "D1"
16 = "#INT"
17 = "#MNI"
18 = "#HALT"
19 = "#MREQ"
20 = "#IORQ"
21 = "#RD"
22 = "#WR"
23 = "#BUSACK"
24 = "#WAIT"
25 = "#BUSREQ"
26 = "#RESET"
27 = "#M1"
28 = "#RFSH"
29 = "GND"
30 = "A0"
31 = "A1"
32 = "A2"
33 = "A3"
34 = "A4"
35 = "A5"
36 = "A6"
37 = "A7"
38 = "A8"
39 = "A9"
40 = "A10"
