# Z86C91 DIP definition
# https://github.com/tgtakaoka/dip
name = "Z86C91"
title = "Z86C91 (Z8)"
dip = 40
width = 600
1 = "VCC"
2 = "XTAL2"
3 = "XTAL1"
4 = "P37, TxD"
5 = "P30, RxD"
6 = "#RESET"
7 = "R/W"
8 = "#DS"
9 = "#AS"
10 = "P35"
11 = "GND"
12 = "P32"
13 = "A8"
14 = "A9"
15 = "A10"
16 = "A11"
17 = "A12"
18 = "A13"
19 = "A14"
20 = "A15"
21 = "AD0"
22 = "AD1"
23 = "AD2"
24 = "AD3"
25 = "AD4"
26 = "AD5"
27 = "AD6"
28 = "AD7"
29 = "P34, #DM"
30 = "P33"
31 = "P20"
32 = "P21"
33 = "P22"
34 = "P23"
35 = "P24"
36 = "P25"
37 = "P26"
38 = "P27"
39 = "P31"
40 = "P36"
